title = "nihilistkitten"
description = "Hi! I'm Riley. My pronouns are she/they. This site serves two purposes: an excuse to play with random web technologies, and a tool to scream meaninglessly into the void."
base_url = "rileyshahar.github.io"
compile_sass = true
taxonomies = [{ name = "tags", paginate_by = 10 }]

# github pages compat
# output_dir = "docs"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
smart_punctuation = true

[extra]
author = "Riley Shahar"
generator = "Zola"
# twitter = "nihilistkitten1"
